Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
import numpy as np

In [48]:
arr = np.array(np.arange(2,50,3).reshape(4,4))
print(arr)

[[ 2  5  8 11]
 [14 17 20 23]
 [26 29 32 35]
 [38 41 44 47]]


Questions 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [26]:
print("First List")
num =input("Enter 5 numbers with space in between")
list1=num.split()
print("Second List")
num =input("Enter 5 numbers with space in between")
list2=(num.split())
print()
list1 = [int(i) for i in list1]
list2 = [int(i) for i in list2]

print("Entered List is :")
print(list1)
print(list2)


First List
Enter 5 numbers with space in between3 4 2 15 4
Second List
Enter 5 numbers with space in between6 4 2 54 3

Entered List is :
[3, 4, 2, 15, 4]
[6, 4, 2, 54, 3]


In [34]:
#conversion into numpy array
n_list1=np.array(list1)
n_list2=np.array(list2)
print(n_list1)
print(n_list2)

[ 3  4  2 15  4]
[ 6  4  2 54  3]


In [43]:
#concatination
concat = np.concatenate((n_list1,n_list2),axis=0)
print(concat)

[ 3  4  2 15  4  6  4  2 54  3]


In [47]:
#sort
sort_np=np.sort(concat)
print(sort_np)

[ 2  2  3  3  4  4  4  6 15 54]


Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [51]:
#creation of numpy array
arr=np.array(np.arange(1,10).reshape(3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
#datatype
arr.dtype

dtype('int32')

In [53]:
#dimension
arr.ndim

2

In [54]:
#size
arr.size

9

In [55]:
#shape
arr.shape

(3, 3)

Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

>use the np.expand() to cnvert the array.
using this 1D will become 2D,

>2D will become 3D
and so on...


In [75]:
arr=np.array(np.arange(1,10))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [115]:
a=np.expand_dims(arr,axis=1)
print(a)
print(a.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
2


>np.newaxis helps to create new axis for the array 
it can create 'n' number of new axis

In [131]:
ze =np.array(np.zeros([2,2]))
print(ze)

[[0. 0.]
 [0. 0.]]


In [135]:
five_dim = ze[np.newaxis, ..., np.newaxis, np.newaxis]

In [137]:
print(five_dim.ndim)
print(five_dim.shape)

5
(1, 2, 2, 1, 1)


Questions 5:
    
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [143]:
array1=np.array(np.arange(4))
array2=np.array(np.arange(4,8))
print(array1)
print(array2)

[0 1 2 3]
[4 5 6 7]


In [145]:
varray=np.vstack((array1,array2))
print(varray)
print(varray.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [146]:
harray =np.hstack((array1,array2))
print(harray)
print(harray.shape)

[0 1 2 3 4 5 6 7]
(8,)


Question 6

How to get unique items and counts of unique items?

In [148]:
arr= np.array([1,2,3,1,3,4,2])
print(arr)

[1 2 3 1 3 4 2]


In [150]:
unique=np.unique(arr)
print(unique)

[1 2 3 4]


In [152]:
unique.size

4